### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by le-jun** [adriantombu/twitter-cleaning#4] opened 2022-12-17 13:45 UTC
Not sure to understand where to put my credentials. Could you further explain?

I went the way I understood and created a repository secret using the bi~iig green button, named it "Parameters" and copy-pasted the `.env.example` file filling in my credentials. Is it the right way to do or:

* should one use "Environment secrets"? 
* should every variable have its own secret?

![Screenshot of the Actions secrets screen showing "Environment secrets" and "Repository secrets". I created a repository one named "Parameters" where the content is a copy of the `.env.example` file](https://user-images.githubusercontent.com/88536727/208244774-6573f37d-0974-479e-9d5e-692d5cace7cb.png)

**Comment by adriantombu** [comment] 2022-12-20 11:41
Hey @le-jun! I'll update the doc to make it easier to understand how to set up the project, there's indeed some lack of proper instructions here.

So to summarize: 
- If you want to run the project locally on your computer, just filling the proper values in an `.env` file will be enough.
- If you want to run the project automatically through GitHub Actions, you need to go to "Settings > Secrets > Actions" and add each of the secrets one by one (see below) in the "Repository secrets" section. No need to use a `.env` file here.

![Screenshot 2022-12-20 at 12 39 36](https://user-images.githubusercontent.com/383297/208658485-800440bf-f3ef-495a-a11c-b1040a07578b.png)

Feel free to ping me if it's still not clear enough, your experience will help me write better documentation once your struggle is resolved.

**Comment by le-jun** [comment] 2022-12-21 07:07
Ok so:

* I think I got my actions’ secrets right. One thing to note is that on TwitterDev the keys given names could be summarised as API, API Secret, Bearer, Access, Access Secret, Client and Client Secret. I guess it would be even easier to understand the which goes where with a 1 to 1 correspondence between names.
* I manually activated the three actions (likes, tweet and cron) just now, each of them getting a green checkmark, but haven’t seen any difference yet on my Twitter post count (still 38 k or so…). Note sure if you’re aware of it, the tweet and like deleting actions got a warning as: "Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-node@v2".

As I didn’t mention it in the first place, a big thanks to you for putting up this solution and providing support!

Edit: One day later, the actions ran again "successfully" but my tweet count still hasn’t changed. Something looks wrong.

**Comment by adriantombu** [comment] 2022-12-23 09:22
- I will update the readme with the 1:1 correspondence, it will be easier to use that way, you're right!
- Regarding the Node.js 12 notice, I'm upgrading my different repositories to newer GitHub Actions, so this will be resolved soon.

Regarding your tweet deletions, I went to look at your fork, and there is an error regarding your credentials (see screenshot below). Twitter has seen many changes during the past few weeks, so maybe something is broken. I'll try to create an app from scratch to see what things have changed to update the readme accordingly.

![Screenshot 2022-12-23 at 10 15 56](https://user-images.githubusercontent.com/383297/209308481-a7a966a4-548a-4ae9-8470-e69704cfa2fd.png)

In the meantime, you can have a look at https://tweetdelete.net/. I used this service last year to delete everything on my profile and then created this script to delete my tweets/like daily. So be advised, I never tested it on an account with more than a dozen tweets 😄 I have another account with 2.5k tweets that I intend to clean in the coming days, so it will help me debug any problem.

**Comment by adriantombu** [comment] 2022-12-23 12:42
I'm working on the documentation, but the developer portal only allows you to create three apps per day (even if you delete them), so it's gonna take a few days because I'm adding/deleting them to check everything is working as expected 😄 

Also, I pushed a potential fix to the above error, but I'll need to continue testing & improving a few things in the coming days.

**Comment by adriantombu** [comment] 2022-12-23 14:35
Well I had a third account waiting for my tests, so here is a new documentation for the Twitter credentials https://github.com/adriantombu/twitter-cleaning/blob/main/TWITTER-CRENDENTIALS.md

And rate limits are now better handled: instead of crashing and waiting the next day run, we now just wait until the limits as been reset to continue deleting the tweets and likes.

I hope it helps, feel free to comment to let me know if it resolved your problem!

**Comment by le-jun** [comment] 2022-12-24 13:01
Yay, seems to work according to the run logs. The issue was probably that I had the Essential dev plan and needed Elevated access as stated (which is a hassle to apply to even if it’s quite simple). Given my looong tweet history it’ll probably take a while before being totally clean though.

**Comment by adriantombu** [comment] 2022-12-24 13:10
Well, with the updated code from yesterday, I just ran the script locally and deleted 2.5k tweets in about 10 minutes without hitting any rate limit, which is strange (it should be 50 tweet deletions per 15 minutes if I refer to the Twitter documentation).

Likes have the 50 deletion / 15 minutes, though, so it will take longer.

I'll close this issue as the problem is resolved now. Thanks for your feedback and enjoy the holidays 🎅🏽

**Closed as completed by adriantombu** 2022-12-24 13:10 UTC
Labels: bug, documentation
